{% set name = "dtool" %}
{% set author = "jic-dtool" %}
{% set version = "3.18.0" %}
{% set sha256 = "755c812e40084efdf50a909b8c1959e72e709aada2def8be8abe5f7e29d1f477" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ author }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dtoolcore
    - dtool_cli
    - dtool_create
    - dtool_info
    - dtool_symlink
    - dtool_http
    - dtool_config

test:
  commands:
    - dtool --help
    - pip check
  requires:
    - pip

about:
  home: http://github.com/{{ author }}/{{ name }}
  license: MIT
  license_file: LICENSE.rst
  summary: 'Dtool is a suite of software for managing scientific data and making it accessible programatically.'

  description: | 
    The dtool command line interface allows one to organise files into datasets and to move datasets between 
    different storage solutions, for example from local disk to remote object storage. Importantly it also 
    provides methods to verify that the transfer has been successful.

    The Python API gives complete access to the data and metadata in a dataset. It makes it easy to create 
    scripts for processing the items, or a subset of items, in a dataset. The Python API also allows
    datasets to be constructed programatically.
  doc_url: https://dtool.readthedocs.io/en/latest/
  dev_url: https://github.com/{{ author }}/{{ name }}

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
