{% set name = "dtool" %}
{% set version = "3.26.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef9135de8c088de2ec7b56555a607efd371897427cb27b8e6a3d4ecff69c482d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dtoolcore ==3.18.0
    - dtool_cli ==0.7.1
    - dtool_create ==0.23.4
    - dtool_info ==0.16.2
    - dtool_symlink ==0.3.1
    - dtool_http ==0.5.1
    - dtool_config ==0.4.1
    - dtool_overlay ==0.3.1
    - dtool_annotation ==0.1.1
    - dtool_tag ==0.1.1

test:
  commands:
    - dtool --help
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jic-dtool/dtool
  license: MIT
  license_file: LICENSE.rst
  summary: Dtool is a suite of software for managing scientific data and making it accessible programatically.

  description: |
    The dtool command line interface allows one to organise files into datasets and to move datasets between 
    different storage solutions, for example from local disk to remote object storage. Importantly it also 
    provides methods to verify that the transfer has been successful.

    The Python API gives complete access to the data and metadata in a dataset. It makes it easy to create 
    scripts for processing the items, or a subset of items, in a dataset. The Python API also allows
    datasets to be constructed programatically.
  doc_url: https://dtool.readthedocs.io/en/latest/
  dev_url: https://github.com/jic-dtool/dtool

extra:
  recipe-maintainers:
    - pvanheus
    - jan-janssen
    - tjelvar-olsson
