travis:
  secure:
    BINSTAR_TOKEN: Hz41/QMT3epUKKb5oJokBOLHG1Zx5RS4kDmlAZGCta7XQxn4OoZ8dL4xk6dZLwF3dbp9pNLB05EYynYf6j3CCt2RmOW7K5y93eT6v/emgJYnEB0RAxBOU4fShuOMCJQly+VZu2zYpyMcFbnyUh4EOi94h2bax0oPhwxnMNQ72DsQ57y+k7nHb2I3mZtpXwyYg9UXSrd1mhIX+zUTHH/i1GC9I9zBxz/KGMaa6MEFbvgEqgwcVHGdAFrQv9KTvo80ujjwSJE1xW7vT6ye3M/XBZqM0wwmgdufUIYYHNcMa1sjzeBVASRkWyYOmdWI2uOPp7cQBPGOhAtGlivh+gc1nYJSGyo5jQ80RtpxNqNNAIl4rTBWTGzoTzLdvg+IiTlx/1/gIyXrrKEOsr/k5heWg3t/Xe86VUMB1ZjyEP4VyvBc2cfr85lPoWpxMvCIB8VOc7TMWISd7etw7v94c4/xbkT7cbWCJwAYUzYL0jwA7R7UL9sd+M0Nj+lh8nJKf6C4NVGrxY3FuZbOUccFYHspfbBaxEgrN1RDmoTvjuYU/2LEJ7RMQ1jPTArlqiddkyhLmSgMlnTH9/3fhyamz1f65/c4TbiLPzsXqWyAeIu9gkBdxt+1suNH+VALSykF011N1Q5g5Nk30HJfPDzBl9Pq+OJuw/PlMS6JKbnzoCN2REw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
